<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageRamen.aspx.cs" Inherits="RAAMEN.View.ManageRamen" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="ramenGV" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowEditing="ramenGV_RowEditing" OnRowDeleting="ramenGV_RowDeleting" runat="server"></asp:GridView>
        </div>
        <div>
            <asp:Button ID="AddBtn" runat="server" Text="Add New Ramen" OnClick="AddBtn_Click" />
        </div>
    </form>
</body>
</html>
